version: '3'
services:
  portfolio:
    build: .
    networks:
      - nginx-proxy-manager_default
    env_file:
      - /home/runner/portfolio.env
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M

networks:
  nginx-proxy-manager_default:
    external: true
