name: Deploy Portfolio to VPS

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Deploy using Docker Compose
        run: |
          docker compose down
          docker compose up -d --build

      - name: Clean up Docker build cache
        run: docker builder prune -a -f
